### ISSUE TITLE
Build for platform

### ISSUE THREAD

**Issue by brunowego** [alvarowolfx/front-in-cuiaba-app#3]
Add instructions for build app for a platform, example: android.

**Comment by brunowego** [comment]
Build command:

``` bash
sudo ionic platform ios
sudo ionic platform android
```

Issue with permission:

``` bash
chmod 777 hooks/after_prepare/010_add_platform_class.js
```

**Comment by alvarowolfx** [comment]
I will add a more detailed instruction to run on simulator. On Mac OS it's really easy to run on iOS simulator, just have Xcode installed and it simple works ( the ionic team recomends to run on iOS first) , but to run on device you need to have a developer account ( unfortunately a $99 fee). To run on Android it's not just add the platform, you have to configure android SDK on your computer path, [this link](http://ccoenraets.github.io/ionic-tutorial/build-ionic-project.html) contains a good tutorial to do this. I will probably inspire on this link to show better instructions. 

And I don't recommend to run commands with sudo, probably your environment ( node and npm) was installed with sudo so some commands are requiring sudo command. You can use NVM ( I never used it but it's one solution), or see [this](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) to resolve the problem.

Thanks for the interest and for helping on this repository.

**Comment by brunowego** [comment]
Nice @alvarowolfx :+1:
